package entities;
// Generated 16-ene-2020 16:32:20 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.json.bind.annotation.JsonbTransient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name = "clientes", catalog = "ceepexpress")
public class Clientes implements java.io.Serializable {

	private Integer idCliente;
	private String nombreCliente;
	private String cifnif;
	private String direccionFacturacion;
	private Set<Envios> envioses = new HashSet<Envios>(0);
	private Set<Destinatarios> destinatarioses = new HashSet<Destinatarios>(0);

	public Clientes() {
	}

	public Clientes(String nombreCliente, String cifnif, String direccionFacturacion) {
		this.nombreCliente = nombreCliente;
		this.cifnif = cifnif;
		this.direccionFacturacion = direccionFacturacion;
	}

	public Clientes(String nombreCliente, String cifnif, String direccionFacturacion, Set<Envios> envioses,
			Set<Destinatarios> destinatarioses) {
		this.nombreCliente = nombreCliente;
		this.cifnif = cifnif;
		this.direccionFacturacion = direccionFacturacion;
		this.envioses = envioses;
		this.destinatarioses = destinatarioses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdCliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "NombreCliente", nullable = false, length = 60)
	public String getNombreCliente() {
		return this.nombreCliente;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

	@Column(name = "CIFNIF", nullable = false, length = 9)
	public String getCifnif() {
		return this.cifnif;
	}

	public void setCifnif(String cifnif) {
		this.cifnif = cifnif;
	}

	@Column(name = "DireccionFacturacion", nullable = false, length = 250)
	public String getDireccionFacturacion() {
		return this.direccionFacturacion;
	}

	public void setDireccionFacturacion(String direccionFacturacion) {
		this.direccionFacturacion = direccionFacturacion;
	}
	@Transient
	@JsonbTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<Envios> getEnvioses() {
		return this.envioses;
	}

	public void setEnvioses(Set<Envios> envioses) {
		this.envioses = envioses;
	}
	
	@Transient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<Destinatarios> getDestinatarioses() {
		return this.destinatarioses;
	}

	public void setDestinatarioses(Set<Destinatarios> destinatarioses) {
		this.destinatarioses = destinatarioses;
	}

}
