package entities;
// Generated 16-ene-2020 16:32:20 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Envios generated by hbm2java
 */
@Entity
@Table(name = "envios", catalog = "ceepexpress")
public class Envios implements java.io.Serializable {

	private Integer idEnvio;
	private Clientes clientes;
	private Estadosenvio estadosenvio;
	private String nombreDestinatario;
	private String dninif;
	private String codigoPostal;
	private String direccionCompleta;
	private int numIntentosEntrega;

	public Envios() {
	}

	public Envios(Clientes clientes, Estadosenvio estadosenvio, String nombreDestinatario, String codigoPostal,
			String direccionCompleta, int numIntentosEntrega) {
		this.clientes = clientes;
		this.estadosenvio = estadosenvio;
		this.nombreDestinatario = nombreDestinatario;
		this.codigoPostal = codigoPostal;
		this.direccionCompleta = direccionCompleta;
		this.numIntentosEntrega = numIntentosEntrega;
	}

	public Envios(Clientes clientes, Estadosenvio estadosenvio, String nombreDestinatario, String dninif,
			String codigoPostal, String direccionCompleta, int numIntentosEntrega) {
		this.clientes = clientes;
		this.estadosenvio = estadosenvio;
		this.nombreDestinatario = nombreDestinatario;
		this.dninif = dninif;
		this.codigoPostal = codigoPostal;
		this.direccionCompleta = direccionCompleta;
		this.numIntentosEntrega = numIntentosEntrega;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdEnvio", unique = true, nullable = false)
	public Integer getIdEnvio() {
		return this.idEnvio;
	}

	public void setIdEnvio(Integer idEnvio) {
		this.idEnvio = idEnvio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCliente", nullable = false)
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdEstadoEnvio", nullable = false)
	public Estadosenvio getEstadosenvio() {
		return this.estadosenvio;
	}

	public void setEstadosenvio(Estadosenvio estadosenvio) {
		this.estadosenvio = estadosenvio;
	}

	@Column(name = "NombreDestinatario", nullable = false, length = 200)
	public String getNombreDestinatario() {
		return this.nombreDestinatario;
	}

	public void setNombreDestinatario(String nombreDestinatario) {
		this.nombreDestinatario = nombreDestinatario;
	}

	@Column(name = "DNINIF", length = 10)
	public String getDninif() {
		return this.dninif;
	}

	public void setDninif(String dninif) {
		this.dninif = dninif;
	}

	@Column(name = "CodigoPostal", nullable = false, length = 10)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "DireccionCompleta", nullable = false, length = 250)
	public String getDireccionCompleta() {
		return this.direccionCompleta;
	}

	public void setDireccionCompleta(String direccionCompleta) {
		this.direccionCompleta = direccionCompleta;
	}

	@Column(name = "NumIntentosEntrega", nullable = false)
	public int getNumIntentosEntrega() {
		return this.numIntentosEntrega;
	}

	public void setNumIntentosEntrega(int numIntentosEntrega) {
		this.numIntentosEntrega = numIntentosEntrega;
	}

}
