package entities;
// Generated 16-ene-2020 16:32:20 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Estadosenvio generated by hbm2java
 */
@Entity
@Table(name = "estadosenvio", catalog = "ceepexpress")
public class Estadosenvio implements java.io.Serializable {

	private String idEstadoEnvio;
	private String descripcionEstado;
	private Set<Envios> envioses = new HashSet<Envios>(0);

	public Estadosenvio() {
	}

	public Estadosenvio(String idEstadoEnvio, String descripcionEstado) {
		this.idEstadoEnvio = idEstadoEnvio;
		this.descripcionEstado = descripcionEstado;
	}

	public Estadosenvio(String idEstadoEnvio, String descripcionEstado, Set<Envios> envioses) {
		this.idEstadoEnvio = idEstadoEnvio;
		this.descripcionEstado = descripcionEstado;
		this.envioses = envioses;
	}

	@Id

	@Column(name = "IdEstadoEnvio", unique = true, nullable = false, length = 10)
	public String getIdEstadoEnvio() {
		return this.idEstadoEnvio;
	}

	public void setIdEstadoEnvio(String idEstadoEnvio) {
		this.idEstadoEnvio = idEstadoEnvio;
	}

	@Column(name = "DescripcionEstado", nullable = false, length = 60)
	public String getDescripcionEstado() {
		return this.descripcionEstado;
	}

	public void setDescripcionEstado(String descripcionEstado) {
		this.descripcionEstado = descripcionEstado;
	}
	
	@Transient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadosenvio")
	public Set<Envios> getEnvioses() {
		return this.envioses;
	}

	public void setEnvioses(Set<Envios> envioses) {
		this.envioses = envioses;
	}

}
